### ISSUE TITLE
这老哥是不是精神错乱

### ISSUE THREAD

**Issue by sagiwei** [caution-996-icu/Caution.996.ICU#10]
RT

**Comment by kasuganosoras** [comment]
不光是精神错乱，怕不是脑子被门夹过，像个傻逼一样天天举报举报 nmlgb
搞完了学习强国那个项目现在又想来搞 996.ICU，怕不是要给真人快打干死

**Comment by SaveMyAss** [comment]
这种人都精明又胆小。这些东西肯定都是挂着梯子发的，也不会用自己平时用的邮箱，要人肉出来真人快打很难。
